// <auto-generated />
using System;
using Contract_Monthly_Claim_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContractMonthlyClaimSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260225140101_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Contract_Monthly_Claim_System.Models.Claim", b =>
                {
                    b.Property<int>("claimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("hourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("hoursWorked")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("statusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("submissionDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("totalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("claimId");

                    b.HasIndex("statusId");

                    b.HasIndex("userId");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            claimId = 1,
                            Notes = "Regular teaching hours",
                            hourlyRate = 150m,
                            hoursWorked = 20m,
                            statusId = 1,
                            submissionDate = new DateTime(2024, 10, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            totalAmount = 3000m,
                            userId = 1
                        },
                        new
                        {
                            claimId = 2,
                            Notes = "Extra marking hours",
                            hourlyRate = 150m,
                            hoursWorked = 15m,
                            statusId = 2,
                            submissionDate = new DateTime(2024, 10, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            totalAmount = 2250m,
                            userId = 1
                        },
                        new
                        {
                            claimId = 3,
                            Notes = "Research supervision",
                            hourlyRate = 175m,
                            hoursWorked = 18m,
                            statusId = 3,
                            submissionDate = new DateTime(2024, 10, 31, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            totalAmount = 3150m,
                            userId = 2
                        },
                        new
                        {
                            claimId = 4,
                            Notes = "Exam preparation",
                            hourlyRate = 175m,
                            hoursWorked = 12m,
                            statusId = 4,
                            submissionDate = new DateTime(2024, 10, 29, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            totalAmount = 2100m,
                            userId = 2
                        });
                });

            modelBuilder.Entity("Contract_Monthly_Claim_System.Models.ClaimStatus", b =>
                {
                    b.Property<int>("statusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("statusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("statusId");

                    b.ToTable("ClaimStatuses");

                    b.HasData(
                        new
                        {
                            statusId = 1,
                            statusName = "Submitted"
                        },
                        new
                        {
                            statusId = 2,
                            statusName = "Approved by Coordinator"
                        },
                        new
                        {
                            statusId = 3,
                            statusName = "Approved by Manager"
                        },
                        new
                        {
                            statusId = 4,
                            statusName = "Rejected by Coordinator"
                        },
                        new
                        {
                            statusId = 5,
                            statusName = "Rejected by Manager"
                        },
                        new
                        {
                            statusId = 6,
                            statusName = "Paid"
                        });
                });

            modelBuilder.Entity("Contract_Monthly_Claim_System.Models.Document", b =>
                {
                    b.Property<int>("documentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("claimId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("fileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("fileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("fileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("uploadDate")
                        .HasColumnType("TEXT");

                    b.HasKey("documentId");

                    b.HasIndex("claimId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Contract_Monthly_Claim_System.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("hourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("passwordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("userRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("userId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            email = "mattjones@university.co.za",
                            firstName = "Matt",
                            hourlyRate = 150.00m,
                            lastName = "Jones",
                            passwordHash = "U035CuWx4TAQr1bQABL5SBFf+/E/MdO5GHdS5+KFixo=",
                            passwordSalt = "hhyaO083w0ZOYl55AuCG6jBRlblbvQ0FkyYJrrd4/UM=",
                            phoneNumber = "+27 11 123 4567",
                            userRole = "Lecturer"
                        },
                        new
                        {
                            userId = 2,
                            email = "crownvic@university.co.za",
                            firstName = "Victoria",
                            hourlyRate = 175.00m,
                            lastName = "Crown",
                            passwordHash = "eeIyLs4GRBSyrsiCs2eyLL0wu1PGBo5NLxFD5uctAGw=",
                            passwordSalt = "FwLcBNqyRwyo3HwgYLfsx/vWhQTKGz7fLBFPOZJEy3A=",
                            phoneNumber = "+27 11 123 4568",
                            userRole = "Lecturer"
                        },
                        new
                        {
                            userId = 3,
                            email = "sarahw@university.co.za",
                            firstName = "Sarah",
                            hourlyRate = 200.00m,
                            lastName = "Wilson",
                            passwordHash = "DP5tg9KEDgPKsmtBD/+0BlazsXNLxPdAwy0lbREzo+4=",
                            passwordSalt = "QXk1gJdTSHSwRihIMCTs9QZ/cHBX0aIIHGmmuDQKnCY=",
                            phoneNumber = "+27 11 123 4569",
                            userRole = "Coordinator"
                        },
                        new
                        {
                            userId = 4,
                            email = "davidb@university.co.za",
                            firstName = "David",
                            hourlyRate = 250.00m,
                            lastName = "Brown",
                            passwordHash = "0mgrLlw+wB23c/ol/jHPBCNtNBljsLeZcG8Di0u6WnY=",
                            passwordSalt = "lrQmJEDmwIAtsXwatTZyVNiOm9/ifk9mpEh20UGgxPE=",
                            phoneNumber = "+27 11 123 4570",
                            userRole = "Manager"
                        },
                        new
                        {
                            userId = 5,
                            email = "hr@university.co.za",
                            firstName = "HR",
                            hourlyRate = 0.00m,
                            lastName = "Administrator",
                            passwordHash = "NWbrGUAGNAw7bpYGgmO7vvznpvo5zNRXjubj5AHNNCQ=",
                            passwordSalt = "Ui+5ik/IJcVUCX8VbUJ8vFDZBblifaW3gIq8FWQxKD0=",
                            phoneNumber = "+27 11 123 4571",
                            userRole = "HR"
                        });
                });

            modelBuilder.Entity("Contract_Monthly_Claim_System.Models.Claim", b =>
                {
                    b.HasOne("Contract_Monthly_Claim_System.Models.ClaimStatus", "Status")
                        .WithMany("Claims")
                        .HasForeignKey("statusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Contract_Monthly_Claim_System.Models.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Contract_Monthly_Claim_System.Models.Document", b =>
                {
                    b.HasOne("Contract_Monthly_Claim_System.Models.Claim", "Claim")
                        .WithMany("Documents")
                        .HasForeignKey("claimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Contract_Monthly_Claim_System.Models.Claim", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Contract_Monthly_Claim_System.Models.ClaimStatus", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("Contract_Monthly_Claim_System.Models.User", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
